return {
    {
        'nvim-treesitter/nvim-treesitter',
        config = function()
            require('nvim-treesitter.configs').setup {
                ensure_installed = {
                    'bash',
                    'c',
                    'cmake',
                    'cpp',
                    'css',
                    'diff',
                    'gitignore',
                    'go',
                    'graphql',
                    'help',
                    'html',
                    'http',
                    'javascript',
                    'jsdoc',
                    'jsonc',
                    'latex',
                    'lua',
                    'markdown',
                    'markdown_inline',
                    'meson',
                    'ninja',
                    'nix',
                    'norg',
                    'python',
                    'query',
                    'regex',
                    'rust',
                    'scss',
                    'sql',
                    'toml',
                    'tsx',
                    'typescript',
                    'yaml',
                    'json',
                },
                highlight = { enable = true },
                indent = { enable = false },
                autopairs = { enable = true },
            }
        end,
    },
}
